### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by ghost** [stbrumme/euler#1]
I tried this solution for Hackerrank Project Euler Problem 218. But it fails for hidden test cases.

**Comment by stbrumme** [comment]
... thats because the Hackerrank problem slightly differs from Project Euler. Please read the problem description very carefully !

**Comment by stbrumme** [comment]
Spoiler: the answer is always 0, no matter what n is. Therefore you can even ignore reading n from STDIN.
The following code just reads q and prints 0 for each  n. It solves all hidden testcases !
```cpp
#include <iostream>
int main() {
    int q;
    std::cin >> q;
    while (q--)
      std::cout << 0 << std::endl;   
    return 0;
}
